import { createCardGame, type CardDef } from '../card-engine/createCardGame';

const CARDS: CardDef[] = [
  { text: 'Ich hab noch nie einen Wecker gestellt und ihn dann 10 Mal weggedrückt.', heat: 1 },
  { text: 'Ich hab noch nie so getan, als hätte ich eine Nachricht nicht gesehen.', heat: 1 },
  { text: 'Ich hab noch nie ein Möbelstück falsch zusammengebaut und es so gelassen.', heat: 1 },
  { text: 'Ich hab noch nie im Supermarkt etwas probiert, bevor ich bezahlt habe.', heat: 1 },
  { text: 'Ich hab noch nie einen ganzen Serien-Staffel an einem Tag geschaut.', heat: 1 },
  { text: 'Ich hab noch nie jemanden gegoogelt, bevor ich ihn getroffen habe.', heat: 1 },
  { text: 'Ich hab noch nie eine Sprachnachricht dreimal neu aufgenommen.', heat: 1 },
  { text: 'Ich hab noch nie behauptet, ein Buch gelesen zu haben, das ich nicht kenne.', heat: 1 },
  { text: 'Ich hab noch nie beim Kartenspiel geschummelt.', heat: 1 },
  { text: 'Ich hab noch nie im Auto laut mitgesungen und dabei jemanden gesehen.', heat: 1 },
  { text: 'Ich hab noch nie einen Kaffee weggeschmissen, weil er zu kalt war.', heat: 1 },
  { text: 'Ich hab noch nie Essen bestellt, obwohl der Kühlschrank voll war.', heat: 1 },
  { text: 'Ich hab noch nie eine Playlist nach einer bestimmten Person benannt.', heat: 2 },
  { text: 'Ich hab noch nie krank gemacht, ohne krank zu sein.', heat: 2 },
  { text: 'Ich hab noch nie jemandem aus dieser Runde einen Screenshot geschickt.', heat: 2 },
  { text: 'Ich hab noch nie ein Date abgesagt, weil ich keine Lust mehr hatte.', heat: 2 },
  { text: 'Ich hab noch nie heimlich das Profil eines Ex angeschaut.', heat: 2 },
  { text: 'Ich hab noch nie im Büro geschlafen.', heat: 2 },
  { text: 'Ich hab noch nie eine Nachricht geschrieben und sofort wieder gelöscht.', heat: 2 },
  { text: 'Ich hab noch nie so getan, als wüsste ich, worüber gerade geredet wird.', heat: 2 },
  { text: 'Ich hab noch nie jemanden geghostet.', heat: 2 },
  { text: 'Ich hab noch nie etwas in einer Prüfung abgeschrieben.', heat: 2 },
  { text: 'Ich hab noch nie in der falschen Bahn gesessen und es erst nach 20 Minuten gemerkt.', heat: 2 },
  { text: 'Ich hab noch nie eine Nachricht an die falsche Person geschickt – und es war schlimm.', heat: 3 },
  { text: 'Ich hab noch nie jemanden aus dieser Runde attraktiv gefunden.', heat: 3 },
  { text: 'Ich hab noch nie jemandem gesagt, ich liebe ihn, ohne es zu meinen.', heat: 3 },
  { text: 'Ich hab noch nie ein Geheimnis weitererzählt, das ich behalten sollte.', heat: 3 },
  { text: 'Ich hab noch nie einen Filmriss gehabt.', heat: 3 },
  { text: 'Ich hab noch nie auf einer Party geweint.', heat: 3 },
  { text: 'Ich hab noch nie etwas mitgehen lassen, das mir nicht gehörte.', heat: 3 },
  { text: 'Ich hab noch nie jemanden geküsst, den ich am nächsten Tag nicht mehr treffen wollte.', heat: 3 },
  { text: 'Ich hab noch nie meine eigenen Regeln für ein Trinkspiel erfunden, um zu gewinnen.', heat: 1 },
];

export const neverHaveIEver = createCardGame({
  id: 'never-have-i-ever',
  name: 'Ich hab noch nie',
  tagline: 'Handy weg. Karte lesen. Ehrlich sein.',
  emoji: '🙈',
  accent: 'var(--teal)',
  minPlayers: 4,
  maxPlayers: 16,
  duration: '10-25 Min',
  intensity: 2,
  tags: ['handy-weg', 'reden'],
  howTo: [
    'Ein Handy liegt in der Mitte, alle anderen bleiben in der Tasche.',
    'Karte vorlesen. Wer es schon gemacht hat, trinkt.',
    'Deine persönliche Menge steht auf deinem Handy – oder du fragst den Vorleser.',
  ],
  actor: 'none',
  baseSips: 3,
  drink: 'self-declare',
  resolveLabel: 'Alle haben getrunken',
  heatSelectable: true,
  cards: CARDS,
});
