export interface TabuWord {
  word: string;
  taboo: string[];
}

export const TABU_WORDS: TabuWord[] = [
  { word: 'Kater', taboo: ['Alkohol', 'Kopfschmerzen', 'Morgen', 'Katze'] },
  { word: 'Festival', taboo: ['Musik', 'Zelt', 'Bühne', 'Sommer'] },
  { word: 'Pfand', taboo: ['Flasche', 'Automat', 'Geld', 'Supermarkt'] },
  { word: 'Tinder', taboo: ['App', 'Wischen', 'Date', 'Match'] },
  { word: 'Döner', taboo: ['Fleisch', 'Fladenbrot', 'Imbiss', 'Soße'] },
  { word: 'Spotify', taboo: ['Musik', 'Playlist', 'Streaming', 'Abo'] },
  { word: 'Sonnenbrand', taboo: ['Haut', 'Sonne', 'Rot', 'Creme'] },
  { word: 'Regenschirm', taboo: ['Regen', 'Nass', 'Wetter', 'Aufspannen'] },
  { word: 'Fahrrad', taboo: ['Rad', 'Treten', 'Lenker', 'Kette'] },
  { word: 'WG-Küche', taboo: ['Wohnung', 'Spülen', 'Mitbewohner', 'Dreckig'] },
  { word: 'Schnarchen', taboo: ['Schlafen', 'Nacht', 'Laut', 'Nase'] },
  { word: 'Bahnstreik', taboo: ['Zug', 'Verspätung', 'Gewerkschaft', 'Deutsche Bahn'] },
  { word: 'Selfie', taboo: ['Foto', 'Handy', 'Kamera', 'Gesicht'] },
  { word: 'Sprachnachricht', taboo: ['WhatsApp', 'Reden', 'Aufnehmen', 'Hören'] },
  { word: 'Karaoke', taboo: ['Singen', 'Mikrofon', 'Bar', 'Text'] },
  { word: 'Kaffeemaschine', taboo: ['Kaffee', 'Bohnen', 'Küche', 'Morgens'] },
  { word: 'Steuererklärung', taboo: ['Finanzamt', 'Geld', 'Formular', 'Jahr'] },
  { word: 'Weckerklingeln', taboo: ['Aufstehen', 'Morgen', 'Handy', 'Schlaf'] },
  { word: 'Umzugskarton', taboo: ['Wohnung', 'Packen', 'Pappe', 'Tragen'] },
  { word: 'Hochzeitstanz', taboo: ['Braut', 'Heiraten', 'Musik', 'Paar'] },
  { word: 'Autobahn', taboo: ['Auto', 'Fahren', 'Tempolimit', 'Stau'] },
  { word: 'Nachbar', taboo: ['Wohnung', 'Nebenan', 'Laut', 'Haus'] },
  { word: 'Fußballtrikot', taboo: ['Sport', 'Verein', 'Anziehen', 'Nummer'] },
  { word: 'Zahnarzt', taboo: ['Zähne', 'Bohrer', 'Termin', 'Praxis'] },
  { word: 'Grillabend', taboo: ['Fleisch', 'Kohle', 'Garten', 'Sommer'] },
  { word: 'Podcast', taboo: ['Hören', 'Folge', 'Reden', 'Radio'] },
  { word: 'Flughafen', taboo: ['Fliegen', 'Koffer', 'Gate', 'Urlaub'] },
  { word: 'Wecker-Snooze', taboo: ['Wecker', 'Nochmal', 'Schlafen', 'Knopf'] },
  { word: 'Lieferdienst', taboo: ['Essen', 'Bestellen', 'App', 'Fahrer'] },
  { word: 'Silvester', taboo: ['Feuerwerk', 'Jahr', 'Mitternacht', 'Party'] },
  { word: 'Schwimmbad', taboo: ['Wasser', 'Schwimmen', 'Becken', 'Bahnen'] },
  { word: 'Erste Hilfe', taboo: ['Verletzt', 'Kurs', 'Notruf', 'Pflaster'] },
  { word: 'Wandern', taboo: ['Berg', 'Laufen', 'Natur', 'Rucksack'] },
  { word: 'Kühlschrank', taboo: ['Kalt', 'Essen', 'Küche', 'Tür'] },
  { word: 'Kopfhörer', taboo: ['Musik', 'Ohren', 'Kabel', 'Hören'] },
  { word: 'Vorstellungsgespräch', taboo: ['Job', 'Bewerbung', 'Chef', 'Fragen'] },
  { word: 'Schnitzeljagd', taboo: ['Suchen', 'Kinder', 'Zettel', 'Spiel'] },
  { word: 'Tattoo', taboo: ['Haut', 'Nadel', 'Studio', 'Motiv'] },
  { word: 'Streaminganbieter', taboo: ['Netflix', 'Serie', 'Abo', 'Schauen'] },
  { word: 'Handyakku', taboo: ['Laden', 'Leer', 'Prozent', 'Kabel'] },
  { word: 'Schwarzfahren', taboo: ['Ticket', 'Bahn', 'Kontrolle', 'Strafe'] },
  { word: 'Ikea', taboo: ['Möbel', 'Schweden', 'Aufbauen', 'Regal'] },
  { word: 'Sonntagsbraten', taboo: ['Fleisch', 'Essen', 'Familie', 'Sonntag'] },
  { word: 'Fahrschule', taboo: ['Auto', 'Führerschein', 'Lernen', 'Prüfung'] },
  { word: 'Wasserpistole', taboo: ['Wasser', 'Spritzen', 'Spielzeug', 'Sommer'] },
  { word: 'Poloshirt', taboo: ['Kragen', 'Shirt', 'Anziehen', 'Knopf'] },
];
